import torch
import pyro
import pyro.poutine as poutine
from pyro.infer import SVI, Trace_ELBO, Predictive
from pyro.infer.autoguide import AutoNormal
from pyro.optim import Adam

def run_parameter_recovery(model, true_params: dict, obs_mapping: dict, 
                           num_samples=1000, num_steps=2000, lr=0.01):
    """
    A general utility script to perform Parameter Recovery on any Pyro DAG.
    
    Args:
        model: The Pyro model function.
        true_params: A dictionary of the parameters you want to hardcode and recover.
                     e.g. {'w_saves': torch.tensor(0.8), 'gp_sigma': torch.tensor(0.5)}
        obs_mapping: A dictionary mapping the model's argument names to the 
                     sample site names generated by the model.
                     e.g. {'cleanSheet_raw': 'cleanSheet', 'saves': 'saves'}
        num_samples: How many artificial data points to generate.
        num_steps: How many iterations of SVI to run.
        lr: Learning rate for the SVI optimizer.
    """
    pyro.clear_param_store()

    # fix parameters
    conditioned_model = poutine.condition(model, data=true_params)

    # ancestral sampling
    print(f"Generating {num_samples} artificial samples using fixed parameters...")
    # randomly sample anything that's not fixed.
    predictive = Predictive(conditioned_model, num_samples=num_samples)
    
    # We call predictive with no arguments to generate pure fake data
    fake_data_traces = predictive()

    # The model function expects specific kwargs (like cleanSheet_raw). 
    # We map the generated site names to these kwargs.
    fake_kwargs = {}
    for arg_name, site_name in obs_mapping.items():
        if site_name in fake_data_traces:
            fake_kwargs[arg_name] = fake_data_traces[site_name].squeeze()
        else:
            raise ValueError(f"Site '{site_name}' not found in generated data. Available: {list(fake_data_traces.keys())}")

    # We use AutoNormal to automatically create a Gaussian posterior for every unobserved parameter
    guide = AutoNormal(model)
    optimizer = Adam({"lr": lr})
    svi = SVI(model, guide, optimizer, loss=Trace_ELBO())

    # Attempt to recover parameters
    print(f"\nRunning SVI for {num_steps} steps to recover parameters...")
    for step in range(num_steps):
        loss = svi.step(**fake_kwargs)
        if step % 500 == 0:
            print(f"Step {step:>4} | Loss: {loss:.2f}")


    print("\n" + "="*45)
    print("        PARAMETER RECOVERY RESULTS")
    print("="*45)
    print(f"{'Parameter':<15} | {'True':>7} | {'Inferred':>8} | {'Error':>6}")
    print("-" * 45)
    
    # Extract the median of the learned posterior distributions
    inferred_medians = guide.median()

    for param_name, true_tensor in true_params.items():
        true_val = true_tensor.item()
        
        if param_name in inferred_medians:
            inferred_val = inferred_medians[param_name].item()
            error = abs(true_val - inferred_val)
            print(f"{param_name:<15} | {true_val:>7.3f} | {inferred_val:>8.3f} | {error:>6.3f}")
        else:
            print(f"{param_name:<15} | {true_val:>7.3f} | NOT FOUND")
            
    print("="*45)
    
    return fake_kwargs, guide
